<?php
/**
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @license https://www.mozilla.org/MPL/2.0/ Mozilla Public License 2.0
 * @link https://github.com/ondrejd/odwp-projects for the canonical source repository
 * @package odwp-projects
 * @since 0.2.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<fieldset class="inline-edit-col-left">
	<div class="inline-edit-group">
		<label>
			<span class="title"><abbr title="<?php _e( 'Aktuální stav projektu', ODWPP_SLUG )?>"><?php _e( 'Stav:', ODWPP_SLUG )?></abbr></span>
			<span class="input-text-wrap">
                <select id="odwpp-project_repository" name="project_status" value="">
            		<option value="active"><?php _e( 'Aktivní', ODWPP_SLUG )?></option>
            		<option value="nonactive"><?php _e( 'Neaktivní', ODWPP_SLUG )?></option>
            		<option value="finished"><?php _e( 'Dokončený', ODWPP_SLUG )?></option>
            		<option value="cancelled"><?php _e( 'Zrušený', ODWPP_SLUG )?></option>
                </select>
            </span>
		</label>
	</div>
</fieldset>
